# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='featured_photo',
            field=models.ImageField(default='', upload_to='forkilla/static/images/'),
        ),
    ]
